<?php

// autoload_classmap.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'Composer\\InstalledVersions' => $vendorDir . '/composer/InstalledVersions.php',
    'Oxxen\\Config' => $baseDir . '/models/Config.class.php',
    'Oxxen\\Database' => $baseDir . '/models/DataBase.class.php',
    'Oxxen\\Functions' => $baseDir . '/models/Functions.class.php',
    'Oxxen\\Route' => $baseDir . '/models/Route.class.php',
);
