<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit1bd71b38f30747ab87dd55a3792c9d1d
{
    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
        'Oxxen\\Config' => __DIR__ . '/../..' . '/models/Config.class.php',
        'Oxxen\\Database' => __DIR__ . '/../..' . '/models/DataBase.class.php',
        'Oxxen\\Functions' => __DIR__ . '/../..' . '/models/Functions.class.php',
        'Oxxen\\Route' => __DIR__ . '/../..' . '/models/Route.class.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->classMap = ComposerStaticInit1bd71b38f30747ab87dd55a3792c9d1d::$classMap;

        }, null, ClassLoader::class);
    }
}
